### ISSUE TITLE
Container doesnt start anymore

### ISSUE THREAD

**Issue by Blueforcer** [tiredofit/docker-flarum#2]
ive restarted my server today and my flaum container wont come up
maybe its possible to log readable error messages :-)?

`++ PHP_ENABLE_WDDX=FALSE

++ PHP_ENABLE_XDEBUG=FALSE

++ PHP_ENABLE_XML=TRUE

++ PHP_ENABLE_XMLREADER=TRUE

++ PHP_ENABLE_XMLRPC=FALSE

++ PHP_ENABLE_XMLWRITER=FALSE

++ PHP_ENABLE_ZIP=FALSE

++ PHP_ENABLE_ZLIB=TRUE

++ PHP_ENABLE_ZMQ=FALSE

++ PHP_FPM_HOST=127.0.0.1

++ PHP_FPM_LISTEN_PORT=9000

++ PHP_FPM_MAX_CHILDREN=75

++ PHP_FPM_MAX_REQUESTS=500

++ PHP_FPM_MAX_SPARE_SERVERS=3

++ PHP_FPM_MIN_SPARE_SERVERS=1

++ PHP_FPM_PROCESS_MANAGER=dynamic

++ PHP_FPM_START_SERVERS=2

++ PHP_LOG_FILE=php-fpm.log

++ PHP_LOG_LEVEL=notice

++ PHP_LOG_LOCATION=/www/logs/php-fpm

++ PHP_MEMORY_LIMIT=512m

++ PHP_OPCACHE_MEM_SIZE=128

++ PHP_POST_MAX_SIZE=2G

++ PHP_TIMEOUT=900

++ PHP_UPLOAD_MAX_SIZE=2G

+++ php-fpm7 -v

+++ head -n 1

+++ awk '{print $2}'

++ PHP_VERSION=7.3.13

++ PHP_WEBROOT=/www/flarum

+ '[' '' '!=' FALSE ']'

++ ++ grep -v '^d'

ls -l /etc/cont-init.d/00-timezone /etc/cont-init.d/01-permissions /etc/cont-init.d/02-zabbix /etc/cont-init.d/03-cron /etc/cont-init.d/04-smtp /etc/cont-init.d/10-nginx /etc/cont-init.d/20-php-fpm /etc/cont-init.d/30-flarum /etc/cont-init.d/99-container

++ wc -l

+ files_init=9

++ expr 9 - 1

+ files_init=8

++ ls ++ grep -v -l '^d'

/tmp/state/00-timezone-init /tmp/state/01-permissions-init /tmp/state/02-zabbix-init /tmp/state/03-cron-init /tmp/state/04-smtp-init /tmp/state/10-nginx-init /tmp/state/20-php-fpm-init /tmp/state/30-flarum-init /tmp/state/99-container-init

++ wc -l

+ init_complete=9

+ '[' 8 '!=' 9 ']'

+ echo '**********************************************************************************************************************'

+ echo '**********************************************************************************************************************'

+ echo '****                                                                                                              ****'

+ echo '****       ERROR - All scripts have not initialized properly - All services are now halted                        ****'

+ echo '****             - Please enter the container find out why the missing *-init state file hasn'\''t been written      ****'

+ echo '****                                                                                                              ****'

+ echo '**********************************************************************************************************************'

+ echo '**********************************************************************************************************************'



'

+ echo /etc/cont-init.d:

**********************************************************************************************************************

**********************************************************************************************************************

****                                                                                                              ****

****       ERROR - All scripts have not initialized properly - All services are now halted                        ****

****             - Please enter the container find out why the missing *-init state file hasn't been written      ****

****                                                                                                              ****

**********************************************************************************************************************

**********************************************************************************************************************

/etc/cont-init.d:

++ ls -x /etc/cont-init.d

++ sed s#99-container##g

+ echo '00-timezone     01-permissions  02-zabbix       03-cron

04-smtp         10-nginx        20-php-fpm      30-flarum'



'

+ echo /tmp/state:

00-timezone     01-permissions  02-zabbix       03-cron

04-smtp         10-nginx        20-php-fpm      30-flarum

/tmp/state:

++ ls -x /tmp/state/00-timezone-init /tmp/state/01-permissions-init /tmp/state/02-zabbix-init /tmp/state/03-cron-init /tmp/state/04-smtp-init /tmp/state/10-nginx-init /tmp/state/20-php-fpm-init /tmp/state/30-flarum-init /tmp/state/99-container-init

/tmp/state/00-timezone-init     /tmp/state/01-permissions-init

+ echo '/tmp/state/00-timezone-init     /tmp/state/01-permissions-init

/tmp/state/02-zabbix-init       /tmp/state/03-cron-init

/tmp/state/04-smtp-init         /tmp/state/10-nginx-init

/tmp/state/02-zabbix-init       /tmp/state/03-cron-init

/tmp/state/04-smtp-init         /tmp/state/10-nginx-init

/tmp/state/20-php-fpm-init      /tmp/state/30-flarum-init

/tmp/state/99-container-init

/tmp/state/20-php-fpm-init      /tmp/state/30-flarum-init
/tmp/state/99-container-init'


'

+ for services in /var/run/s6/services/[0-9]*
+ s6-svc -d /var/run/s6/services/02-zabbix
+ for services in /var/run/s6/services/[0-9]*
+ s6-svc -d /var/run/s6/services/03-cron
+ for services in /var/run/s6/services/[0-9]*
+ s6-svc -d /var/run/s6/services/04-smtp
+ for services in /var/run/s6/services/[0-9]*
+ s6-svc -d /var/run/s6/services/10-nginx
+ for services in /var/run/s6/services/[0-9]*
+ s6-svc -d /var/run/s6/services/20-php-fpm
+ exit 1

[cont-init.d] 99-container: exited 1.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

`

**Comment by tiredofit** [comment]
Those messages are fairly illegible to anyone but myself sadly. It does look like you are using a very old image, maybe not on purpose, perhaps Docker has not rebuilt the images.
I'll help with decoding all of that mess, can you get me the entire log sent over to my private email - it's in the Changelog.

**Comment by Blueforcer** [comment]
Thanks for your Quick reply.
Unfortunately i didnt find any email adress
Im using the "latest" tag and this is the whole log. Nothing else.

It looks like a similar error as my issue in the mariaDB tag (Wich is working now)
https://github.com/tiredofit/docker-mariadb/issues/3

**Comment by tiredofit** [comment]
Try a `docker-compose pull` or pull the latest `tiredofit/flarum:latest` if you can. I've just modernized the image with some of the upstream base image changes and trimmed the fat.
It should auto upgrade you to 0.10-beta12 as well.

**Comment by Blueforcer** [comment]
Yeay! This works! Thank you
Unfortunally no extension is loaded. even if i install a new one it wont show up in the extension board

**Comment by Blueforcer** [comment]
I think you trimmed too much? :)
```

[NOTICE] ** [flarum] Extensions: Installing fof/links
+ silent composer require fof/links
+ '[' true = TRUE ']'
+ '[' true = true ']'
+ composer require fof/links

    1/2:	http://repo.packagist.org/p/provider-latest$f49fb1d82390e3bf2c7bf339ec92b75a6b68c163eca081f0f1ab580ea96d13a7.json
    2/2:	http://repo.packagist.org/p/provider-2020-01$ac60517f7ba6e70b3029fb092818810def30ffd672a71caa7be4e4a402abd5e0.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Using version ^0.2.1 for fof/links
./composer.json has been updated

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - intervention/image 2.5.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.

    - intervention/image 2.5.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.

    - intervention/image 2.5.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.

    - Installation request for intervention/image (locked at 2.5.1) -> satisfiable by intervention/image[2.5.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php7/php.ini
    - /etc/php7/conf.d/00_bcmath.ini
    - /etc/php7/conf.d/00_ctype.ini
    - /etc/php7/conf.d/00_curl.ini
    - /etc/php7/conf.d/00_dom.ini
    - /etc/php7/conf.d/00_gd.ini
    - /etc/php7/conf.d/00_iconv.ini
    - /etc/php7/conf.d/00_intl.ini
    - /etc/php7/conf.d/00_json.ini
    - /etc/php7/conf.d/00_mbstring.ini
    - /etc/php7/conf.d/00_opcache.ini
    - /etc/php7/conf.d/00_openssl.ini
    - /etc/php7/conf.d/00_pdo.ini
    - /etc/php7/conf.d/00_pgsql.ini
    - /etc/php7/conf.d/00_session.ini
    - /etc/php7/conf.d/00_tokenizer.ini
    - /etc/php7/conf.d/00_xml.ini
    - /etc/php7/conf.d/00_zip.ini
    - /etc/php7/conf.d/01_imap.ini
    - /etc/php7/conf.d/01_mysqlnd.ini
    - /etc/php7/conf.d/01_phar.ini
    - /etc/php7/conf.d/01_xmlreader.ini
    - /etc/php7/conf.d/02_mysqli.ini
    - /etc/php7/conf.d/02_pdo_mysql.ini
    - /etc/php7/conf.d/apcu.ini
    - /etc/php7/conf.d/mcrypt.ini
    - /etc/php7/conf.d/smtp.ini
    - /etc/php7/conf.d/timezone.ini
```

**Comment by tiredofit** [comment]
Not a problem, in short term you can add PHP_ENABLE_FILEINFO=TRUE to your environment variables. I will add it directly into the image.

**Comment by tiredofit** [comment]
New build being built `tiredofit/flarum:1.4.2` or `tiredofit/flarum:latest`

**Comment by tiredofit** [comment]
If you run into any extension install issues let me know, but to diagnose and try on your own you can have a peek at all the other extensions that can be enabled for PHP here: https://github.com/tiredofit/docker-nginx-php-fpm/blob/7.3/README.md

**Comment by Blueforcer** [comment]
Awseome! Everything is working again! Thank you very very much for your help and this nice container!
